# Generated by Django 5.1.1 on 2024-11-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeydew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, default='https://imgur.com/gallery/mare-foal-fhv3QDB#/t/art', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='github_activity_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
