# Generated by Django 5.1.1 on 2024-11-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeydew', '0003_alter_author_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='password',
            new_name='their_password',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='username',
            new_name='their_username',
        ),
        migrations.AddField(
            model_name='node',
            name='our_password',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='our_username',
            field=models.CharField(blank=True, default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
