# Generated by Django 5.1.1 on 2024-12-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeydew', '0004_rename_password_node_their_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.URLField(blank=True, default='https://i.imgur.com/tEyA1Xc.jpeg', max_length=4096, null=True),
        ),
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=4096)),
                ('letter', models.CharField(max_length=4096)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='honeydew.node')),
            ],
        ),
    ]
